server:
  address: "localhost:8000"

auth:
  hash_salt: "hash_salt"
  access_signing_key: "access_signing_key"
  refresh_signing_key: "refresh_signing_key"
  access_token_ttl: 300 # 5 min
  refresh_token_ttl: 1296000 # 15 day

projectPage:
  scratchLink: "0.0.0.0:8601/"

postgres:
  postgresDsn: "host=localhost port=5432 user=robbo password=robbo_pwd dbname=robbo_db"